version: "1"
services:
  db-mysql:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQLDB_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQLDB_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  app-backend:
    depends_on:
    - db-mysql
    restart: on-failure
    build:
      context: ./medilabosolutions-backend
      dockerfile: Dockerfile
    env_file: ./.env
    image: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - $SPRING_LOCAL_PORT_BACKEND:$SPRING_DOCKER_PORT_BACKEND

  app-gateway:
    restart: on-failure
    build:
      context: ./medilabosolutions-gateway
      dockerfile: Dockerfile
    env_file: ./.env
    image: gateway
    environment:
      - spring.cloud.gateway.routes[0].id=backend-route
      - spring.cloud.gateway.routes[0].uri=http://app-backend:$SPRING_LOCAL_PORT_BACKEND
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/backend/**
      - spring.cloud.gateway.routes[1].id=frontend-route
      - spring.cloud.gateway.routes[1].uri=http://app-frontend:$SPRING_LOCAL_PORT_FRONTEND
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/frontend/**
    ports:
      - $SPRING_LOCAL_PORT_GATEWAY:$SPRING_DOCKER_PORT_GATEWAY

  app-frontend:
    restart: on-failure
    build:
      context: ./medilabosolutions-frontend
      dockerfile: Dockerfile
    env_file: ./.env
    image: frontend
    ports:
      - $SPRING_LOCAL_PORT_FRONTEND:$SPRING_DOCKER_PORT_FRONTEND

volumes:
  db: